#!/usr/bin/env python3
"""
Codex를 통한 이미지 생성 예제
Claude Code + Codex 연결을 활용한 무료 이미지 생성
"""

from PIL import Image, ImageDraw, ImageFilter
import os
from datetime import datetime

def generate_landscape_image():
    """Codex 스타일: 아름다운 풍경 이미지 생성"""

    # 이미지 크기: 1280x720 (HD)
    width, height = 1280, 720

    # 배경 생성 (하늘 그라디언트)
    img = Image.new('RGB', (width, height))
    pixels = img.load()

    # 그라디언트 하늘 (주황색 → 파란색)
    for y in range(height):
        # 주황색(FFB347) → 파란색(4A90E2)로 그라디언트
        r = int(255 - (255 - 74) * (y / height))
        g = int(179 - (179 - 144) * (y / height))
        b = int(55 + (226 - 55) * (y / height))

        for x in range(width):
            pixels[x, y] = (r, g, b)

    # Draw 객체 생성
    draw = ImageDraw.Draw(img)

    # 산 그리기 (어두운 녹색)
    mountain_points = [
        (0, 500),
        (400, 200),
        (800, 350),
        (1280, 300),
        (1280, 720),
        (0, 720)
    ]
    draw.polygon(mountain_points, fill=(34, 139, 34))

    # 태양 그리기 (주황색 원)
    sun_bbox = [900, 100, 1050, 250]
    draw.ellipse(sun_bbox, fill=(255, 165, 0))

    # 반사광 추가
    draw.ellipse([920, 120, 1030, 230], fill=(255, 200, 100))

    # 텍스트 추가
    text = f"Generated by Codex + Claude Code\n{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    draw.text((50, 50), text, fill=(255, 255, 255))

    # 블러 효과 (선택)
    img = img.filter(ImageFilter.GaussianBlur(radius=2))

    # 저장
    output_path = '/tmp/codex_landscape_generated.png'
    img.save(output_path)

    print(f"✅ 이미지 생성 완료!")
    print(f"📍 저장 위치: {output_path}")
    print(f"📏 크기: {width}x{height}")
    print(f"💾 파일 크기: {os.path.getsize(output_path) / 1024:.1f} KB")

    return output_path

if __name__ == "__main__":
    generate_landscape_image()
